title: Mi sitio web sencillo
description: PÃ¡gins creada con Jekyll y Github Pages
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
